//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisTakip.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KayitGoster {
            get {
                return ((bool)(this["KayitGoster"]));
            }
            set {
                this["KayitGoster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MalzemeGoster {
            get {
                return ((bool)(this["MalzemeGoster"]));
            }
            set {
                this["MalzemeGoster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MailYolla {
            get {
                return ((bool)(this["MailYolla"]));
            }
            set {
                this["MailYolla"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CihazlariGoster {
            get {
                return ((bool)(this["CihazlariGoster"]));
            }
            set {
                this["CihazlariGoster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GIciCihazlar {
            get {
                return ((bool)(this["GIciCihazlar"]));
            }
            set {
                this["GIciCihazlar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GDisiCihazlar {
            get {
                return ((bool)(this["GDisiCihazlar"]));
            }
            set {
                this["GDisiCihazlar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Yapilacak {
            get {
                return ((bool)(this["Yapilacak"]));
            }
            set {
                this["Yapilacak"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GetirenGoster {
            get {
                return ((bool)(this["GetirenGoster"]));
            }
            set {
                this["GetirenGoster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AksesuarGoster {
            get {
                return ((bool)(this["AksesuarGoster"]));
            }
            set {
                this["AksesuarGoster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TelefonGoster {
            get {
                return ((bool)(this["TelefonGoster"]));
            }
            set {
                this["TelefonGoster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MailGoster {
            get {
                return ((bool)(this["MailGoster"]));
            }
            set {
                this["MailGoster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ModelDetayGoster {
            get {
                return ((bool)(this["ModelDetayGoster"]));
            }
            set {
                this["ModelDetayGoster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ImalKoduGoster {
            get {
                return ((bool)(this["ImalKoduGoster"]));
            }
            set {
                this["ImalKoduGoster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TeknisyenGoster {
            get {
                return ((bool)(this["TeknisyenGoster"]));
            }
            set {
                this["TeknisyenGoster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IdGoster {
            get {
                return ((bool)(this["IdGoster"]));
            }
            set {
                this["IdGoster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DolapNumarasiGoster {
            get {
                return ((bool)(this["DolapNumarasiGoster"]));
            }
            set {
                this["DolapNumarasiGoster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SıraNumarasiGoster {
            get {
                return ((bool)(this["SıraNumarasiGoster"]));
            }
            set {
                this["SıraNumarasiGoster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StokSayisiGoster {
            get {
                return ((bool)(this["StokSayisiGoster"]));
            }
            set {
                this["StokSayisiGoster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KritikStokGoster {
            get {
                return ((bool)(this["KritikStokGoster"]));
            }
            set {
                this["KritikStokGoster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TedarikciGoster {
            get {
                return ((bool)(this["TedarikciGoster"]));
            }
            set {
                this["TedarikciGoster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RaporlarAksesuarGoster {
            get {
                return ((bool)(this["RaporlarAksesuarGoster"]));
            }
            set {
                this["RaporlarAksesuarGoster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RaporlarTelefonGoster {
            get {
                return ((bool)(this["RaporlarTelefonGoster"]));
            }
            set {
                this["RaporlarTelefonGoster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RaporlarMailGoster {
            get {
                return ((bool)(this["RaporlarMailGoster"]));
            }
            set {
                this["RaporlarMailGoster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RaporlarImalKoduGoster {
            get {
                return ((bool)(this["RaporlarImalKoduGoster"]));
            }
            set {
                this["RaporlarImalKoduGoster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RaporlarKArgoUcretiGoster {
            get {
                return ((bool)(this["RaporlarKArgoUcretiGoster"]));
            }
            set {
                this["RaporlarKArgoUcretiGoster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AtolyeMailGoster {
            get {
                return ((bool)(this["AtolyeMailGoster"]));
            }
            set {
                this["AtolyeMailGoster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AtolyeKargoUcretiGoster {
            get {
                return ((bool)(this["AtolyeKargoUcretiGoster"]));
            }
            set {
                this["AtolyeKargoUcretiGoster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KullaniciYetki {
            get {
                return ((string)(this["KullaniciYetki"]));
            }
            set {
                this["KullaniciYetki"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DbAdi {
            get {
                return ((string)(this["DbAdi"]));
            }
            set {
                this["DbAdi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DbIp {
            get {
                return ((string)(this["DbIp"]));
            }
            set {
                this["DbIp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DbKullaniciAdi {
            get {
                return ((string)(this["DbKullaniciAdi"]));
            }
            set {
                this["DbKullaniciAdi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DbKullaniciSifre {
            get {
                return ((string)(this["DbKullaniciSifre"]));
            }
            set {
                this["DbKullaniciSifre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArizaSebebi {
            get {
                return ((string)(this["ArizaSebebi"]));
            }
            set {
                this["ArizaSebebi"] = value;
            }
        }
    }
}
